export const AUTH_TEXT = {
    common: {
        emailLabel: "อีเมล",
        emailPlaceholder: "your@email.com",
        passwordLabel: "รหัสผ่าน",
        confirmPasswordLabel: "ยืนยันรหัสผ่าน",
        usernameLabel: "ชื่อผู้ใช้",
        usernamePlaceholder: "ชื่อที่แสดงให้ผู้อื่นเห็น",
        phoneLabel: "เบอร์โทรศัพท์",
        phonePlaceholder: "08x-xxx-xxxx",
    },
    password: {
        requirementsHint:
            "ใช้อย่างน้อย 8 ตัวอักษร และต้องมีตัวพิมพ์ใหญ่ ตัวพิมพ์เล็ก ตัวเลข และอักขระพิเศษ",
        placeholders: {
            password: "อย่างน้อย 8 ตัว มี A-Z, a-z, 0-9 และอักขระพิเศษ",
            confirmPassword: "กรอกรหัสผ่านอีกครั้ง",
            currentPassword: "รหัสผ่าน",
        },
        toggleAriaLabels: {
            show: "แสดงรหัสผ่าน",
            hide: "ซ่อนรหัสผ่าน",
            showConfirm: "แสดงยืนยันรหัสผ่าน",
            hideConfirm: "ซ่อนยืนยันรหัสผ่าน",
        },
        validationErrors: {
            required: "กรุณากรอกรหัสผ่าน",
            minLength: "รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร",
            uppercase: "รหัสผ่านต้องมีตัวพิมพ์ใหญ่อย่างน้อย 1 ตัว",
            lowercase: "รหัสผ่านต้องมีตัวพิมพ์เล็กอย่างน้อย 1 ตัว",
            number: "รหัสผ่านต้องมีตัวเลขอย่างน้อย 1 ตัว",
            specialCharacter: "รหัสผ่านต้องมีอักขระพิเศษอย่างน้อย 1 ตัว เช่น ! @ #",
        },
        strengthLabels: {
            veryWeak: "อ่อนมาก",
            weak: "อ่อน",
            medium: "ปานกลาง",
            strong: "แข็งแรง",
            veryStrong: "แข็งแรงมาก",
        },
    },
    login: {
        title: "เข้าสู่ระบบ",
        subtitle: "เข้าสู่ระบบเพื่อซื้อขายสินค้า",
        submit: "เข้าสู่ระบบ",
        loading: "กำลังเข้าสู่ระบบ...",
        emptyCredentials: "กรุณากรอกอีเมลและรหัสผ่าน",
        failed: "เข้าสู่ระบบไม่สำเร็จ",
        noAccount: "ยังไม่มีบัญชี?",
        signUp: "สมัครสมาชิก",
        backHome: "กลับหน้าแรก",
    },
    register: {
        title: "สมัครสมาชิก",
        subtitle: "สร้างบัญชีเพื่อเริ่มซื้อขาย",
        submit: "สมัครสมาชิก",
        loading: "กำลังสมัคร...",
        fillAllFields: "กรุณากรอกข้อมูลให้ครบ",
        haveAccount: "มีบัญชีอยู่แล้ว?",
        signIn: "เข้าสู่ระบบ",
        backHome: "กลับหน้าแรก",
        failed: "สมัครสมาชิกไม่สำเร็จ",
        usernameRequired: "กรุณากรอกชื่อผู้ใช้",
        emailRequired: "กรุณากรอกอีเมล",
        invalidEmail: "รูปแบบอีเมลไม่ถูกต้อง",
        phoneRequired: "กรุณากรอกเบอร์โทรศัพท์",
        phoneMustStartWithZero: "เบอร์โทรศัพท์ต้องขึ้นต้นด้วย 0",
        phoneMustBeTenDigits: "เบอร์โทรศัพท์ต้องมี 10 หลัก",
        passwordMismatch: "รหัสผ่านไม่ตรงกัน",
        shippingAddressTitle: "ที่อยู่สำหรับจัดส่ง",
        addressDetailLabel: "บ้านเลขที่ / ซอย / ถนน",
        addressDetailPlaceholder: "เช่น 123/4 ซอยสุขุมวิท 11 ถนนสุขุมวิท",
        addressRequired: "กรุณากรอกที่อยู่",
        provinceLabel: "จังหวัด",
        provincePlaceholder: "-- เลือกจังหวัด --",
        provinceRequired: "กรุณาเลือกจังหวัด",
        districtLabel: "เขต / อำเภอ",
        districtPlaceholder: "-- เลือกเขต/อำเภอ --",
        districtRequired: "กรุณาเลือกเขต/อำเภอ",
        postalCodeLabel: "รหัสไปรษณีย์",
        postalCodePlaceholder: "เช่น 10110",
        optional: "(ไม่บังคับ)",
        emailOtpTitle: "ยืนยันอีเมล",
        emailOtpSubtitle: "ยืนยันตัวตนด้วยรหัส OTP ทางอีเมล",
        emailAutoLoginFailed: "เข้าสู่ระบบอัตโนมัติไม่สำเร็จ กรุณาเข้าสู่ระบบด้วยตัวเอง",
        emailSkip: "ข้ามขั้นตอนนี้ ไปหน้าเข้าสู่ระบบ",
        phoneOtpTitle: "ยืนยันเบอร์โทรศัพท์",
        phoneOtpSubtitle: "ยืนยันเบอร์โทรศัพท์เพื่อเริ่มซื้อขาย",
        phoneVerifyFailed: "ยืนยันเบอร์โทรไม่สำเร็จ",
        phoneSkip: "ข้ามขั้นตอนนี้",
    },
    modal: {
        title: "เริ่มต้นใช้งาน",
        emailOption: "เข้าสู่ระบบด้วยอีเมล",
        googleComingSoon: "เชื่อมต่อด้วย Google (เร็ว ๆ นี้)",
        back: "กลับ",
        acceptPrefix: "กด",
        acceptMiddle: "เพื่อยอมรับ",
        termsOfService: "เงื่อนไขการใช้บริการ",
        privacyPolicy: "นโยบายความเป็นส่วนตัว",
        and: "และ",
    },
} as const;
